version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: react_native_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: react_native_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
