version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: symfony_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
