version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - database

  backend:
    build:
      context: ./back-symfony
      dockerfile: Dockerfile
    container_name: app_backend
    volumes:
      - ./back-symfony:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8090:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://app_user:app_password@database:3306/app_db
    command: >+
      sh -c "composer install &&
              php bin/console doctrine:database:sch --if-not-exists &&
              php bin/console doctrine:migrations:migrate --no-interaction &&
              php bin/console doctrine:fixtures:load --no-interaction || true &&
              php -S 0.0.0.0:8000 -t public/"
              
  frontend:
    build:
      context: ./front-react-native/basketbrain
      dockerfile: Dockerfile
    container_name: app_frontend
    volumes:
      - ./front-react-native/basketbrain:/app
      - /app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.1
      - API_URL=http://backend:8000

volumes:
  db_data:
